#!/bin/sh

KEY="/etc/hikariconnect/$LOGNAME/dvg_id"
MODE=0

#while getopts o:s opts 
#do  case "$opts" in
#    o)  OTF="$OPTARG";;
#    s)  MODE=1;;
#    [?])    echo "Failed: please specify an OTF after '-o ' (either dv100, dv60, or omx100)"; exit 1;;
#    esac
#done  

#if (test -z $OTF)
#    then echo "Failed: please specify an OTF after '-o ' (either dv100, dv60, or omx100)"
#    exit 1
#fi
#shift $((OPTIND-1))

   ### replaced all this with /opt/bin/otfname for auto-otf-finding

for FNAME in $@ 
do
echo "Working: $FNAME"    
/opt/bin/mkMRCtype0 $FNAME  ## needed so that ccdcor can recognize the extended header.
/opt/bin/mkMRCtime0 $FNAME  ## needed so that decon doesn't bork on hikari 20130611pmc
FULLNAME=${PWD}/${FNAME}
QFNAME=$LOGNAME.`basename $FNAME`.`date +%Y-%m-%d.%H%M%S`
OTFNAME=`/opt/bin/otffind $FNAME`  ## based on lens ID in header

cat - >> /data2/hikari-queue/$QFNAME << EOF
{ test -r '/share/apps/IVE/priism-4.2.9/Priism_setup.sh' && . '/share/apps/IVE/priism-4.2.9/Priism_setup.sh' ; } || exit 1
umask 002
#ccdcor
ccdcor /share/$FULLNAME /share/${FULLNAME}_cor /share/$FULLNAME.plt -norder=4:4:4:4:4 -nout=0:0:0:0:0 -polyfit=1:1:1:1:1 -photon=1:1:1:1:1 -bleach=1:1:1:1:1 -zline=1:1:1:1:1
#mv /share/${FULLNAME}_cor /share/${FULLNAME}

#20130610pmc
#command file for decon

tries=0
while test \$((\$tries)) -lt 10;
do
echo "try \$tries"
( time decon \
 "/share/${FULLNAME}_cor" \
 "/share/${FULLNAME}_decon" \
 "/share/apps/IVE/$OTFNAME"  -ncycl=15 -apodize=8  \
 -nsmod=5 -mode2 -method="DAA" \
 -remap="none" -smooth=0.15:0.8 \
 -wiener=0.9 -prefilter=0.3:0.22 -scale=1 -depth=0 -nmount=1.513 \
 >"/share/$FULLNAME.deconlog" 2>&1
 )

hostname >> /share/$FULLNAME.deconlog
date >> /share/$FULLNAME.deconlog
echo "try_round: \$tries" >> /share/$FULLNAME.deconlog

tries=\`perl /share/apps/IVE/testdeconlog.pl /share/$FULLNAME.deconlog \$tries\`

done

rm /share/${FULLNAME}_cor
EOF

QFNAMEMOD="/share/data2/hikari-queue/$QFNAME"

ssh -i $KEY -nx dvguest@hikari qsub -cwd $QFNAMEMOD
#echo "Would do: ssh -i $KEY -nx dvguest@hikari qsub -cwd $QFNAMEMOD"

done

